---
title: "Mentahan Dashboard DA"
author: "Anggit Novietasari"
date: "7/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      comment = "#>")
```

# DATA EXPLORASI RAWAT JALAN
## Data Wrangling

```{r}
library(tidyverse)
library(glue)
library(plotly)
library(lubridate)
library(xtable)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(ggthemes)
library(data.table)
library(scales)
library(tidyr)
library(ggrepel)
library(leaflet)
library(writexl)
library(Hmisc)
library(cluster)
library(factoextra)
library(Rtsne)
library(gganimate)
library(xlsx)

data <- read.csv("rajal.csv", stringsAsFactors = F)
data

```

```{r}
#type data
wtrj_clean <- data %>% 
  mutate_at(.vars = c("ID.Kunjungan", 
                      "Nomor.RM", 
                      "Nama.RM", 
                      "Nama.Dokter", 
                      "Spesialis"),
            .funs = as.factor) %>% 
  mutate(Tgl..Masuk.Resep = ymd_hms(Tgl..Masuk.Resep),
         Tgl..Input.Medis = ymd_hms(Tgl..Input.Medis),
         Tgl..Input.Telaah.Resep = ymd_hms(Tgl..Input.Telaah.Resep),
         Tgl..Input.Persiapan.Obat.Jadi = ymd_hms(Tgl..Input.Persiapan.Obat.Jadi),
         Tgl..Input.Persiapan.Obat.Racik = ymd_hms(Tgl..Input.Persiapan.Obat.Racik),
         Tgl..Input.Pengecekan.Etiket = ymd_hms(Tgl..Input.Pengecekan.Etiket),
         Tgl..Input.Penyerahan.Obat = ymd_hms(Tgl..Input.Penyerahan.Obat),
         Bulan = months(Tgl..Input.Telaah.Resep),
         Bulan = as.factor(Bulan),
         Tanggal = day(Tgl..Input.Telaah.Resep),
         Hari = weekdays(Tgl..Input.Telaah.Resep),
         jam_telaah_resep = hour(Tgl..Input.Telaah.Resep),
         jam_resep_dokter  = hour(Tgl..Masuk.Resep),
         jam_etiket = hour(Tgl..Input.Pengecekan.Etiket),
         jam_penyerahan_obat = hour(Tgl..Input.Penyerahan.Obat),
         input_medis_resep=as.numeric(difftime(time1 = Tgl..Masuk.Resep,time2 = Tgl..Input.Medis, units = "mins")),
         Input_telaah_resep= as.numeric(difftime(time1 = Tgl..Input.Telaah.Resep, time2 = Tgl..Masuk.Resep, units = "mins")),
         pio = as.numeric(difftime(time1 = Tgl..Input.Penyerahan.Obat, time2 = Tgl..Masuk.Resep, units = "mins")),
         telaah_etiket = as.numeric(difftime(time1 = Tgl..Input.Pengecekan.Etiket, time2 = Tgl..Input.Telaah.Resep, units = "mins")),
         etiket_penyerahan = as.numeric(difftime(time1 = Tgl..Input.Penyerahan.Obat, time2 = Tgl..Input.Pengecekan.Etiket, units= "mins")),
         telaah_serah = as.numeric(difftime(time1 = Tgl..Input.Penyerahan.Obat, time2 = Tgl..Input.Telaah.Resep, units="mins"))
         ) %>% 
  distinct(ID.Kunjungan,.keep_all = T) %>% 
  filter(between(pio,0,1080) &
         between(telaah_serah,0,1080))%>%
           #Input_telaah_resep,0,1080) &
           #between(telaah_etiket,0,1080)&
           #between(etiket_penyerahan,0,1080)&
    filter(!Spesialis %in% c('UMUM','FISIOTERAPI'))
wtrj_clean <- wtrj_clean %>% 
  select(ID.Kunjungan, Nomor.RM,Nama.RM,Nama.Dokter,Spesialis,Tgl..Registrasi, Tgl..Input.Medis, Tgl..Masuk.Resep,Tgl..Input.Telaah.Resep,Tgl..Input.Persiapan.Obat.Jadi, Tgl..Input.Persiapan.Obat.Racik,Tgl..Input.Pengecekan.Etiket,Tgl..Input.Penyerahan.Obat,Bulan, Tanggal, Hari, jam_telaah_resep, jam_resep_dokter,jam_etiket, jam_penyerahan_obat, pio, telaah_etiket, etiket_penyerahan, Input_telaah_resep, input_medis_resep, telaah_serah) %>% 
  drop_na(Tgl..Masuk.Resep, Tgl..Input.Medis, Tgl..Input.Telaah.Resep)  %>% 
  mutate(Hari = as.factor(Hari))
wtrj_clean
  
```


```{r}

#write.table(wtrj_clean, "wtrj.csv", sep = ",")
```

```{r}
datawtrj <- wtrj_clean %>% 
  select(ID.Kunjungan, Nomor.RM, Nama.Dokter, Spesialis, Tgl..Registrasi, Bulan, Tanggal, Hari, jam_telaah_resep, jam_resep_dokter, jam_etiket, jam_penyerahan_obat, pio, telaah_etiket, etiket_penyerahan, Input_telaah_resep, input_medis_resep, telaah_serah)
datawtrj
```

```{r}
#write.table(datawtrj, "datawtrj.csv", sep = ",")
```

```{r}
datawtrj_total <- datawtrj %>% 
  group_by(Bulan) %>% 
  summarise(total=n())  %>% 
  ungroup()
datawtrj_total$Bulan <- factor(datawtrj_total$Bulan, levels = c("April","May","June"))
datawtrj_total %>% 
  arrange(Bulan)

hist_total<- plot_ly(datawtrj_total, 
                          x = ~Bulan, 
                          y = ~total, 
                          type = 'bar', 
                          name = 'Bulan',
             marker = list(color = 'rgb(149,173,160)',
                           line = list(color = 'rgb(74,86,80)',
                                       width = 1.5)))
hist_total  <- hist_total  %>% layout(title = "TOTAL KUNJUNGAN PER-BULAN",
         xaxis = list(title = "BULAN"),
         yaxis = list(title = "JUMLAH PASIEN"))
hist_total

```

```{r}
#JAM RESEP DOKTER
resep_dokter <- datawtrj %>%
  group_by(jam_resep_dokter, Hari, Tanggal) %>% 
  summarise(jumlah = n()) %>% 
  mutate(persen = jumlah*100/nrow(wtrj_clean),
         Tanggal = as.factor(Tanggal),
         jam_resep_dokter = as.factor(jam_resep_dokter)) %>% 
  ungroup() %>% 
    filter(!jam_resep_dokter %in% c('5','6','7','21','22','23'))
resep_dokter$Hari <- factor(resep_dokter$Hari, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))
resep_dokter %>% 
  arrange(Hari)
```


```{r}
#JAM RESEP DOKTER
plot_resep_dokter <- ggplot(resep_dokter, aes(x = jam_resep_dokter, y = jumlah, fill=jam_resep_dokter)) +
  geom_boxplot() +
  scale_y_continuous(labels = label_number())+
  facet_wrap(~Hari, ncol=7)
ggplotly(plot_resep_dokter)
```

